import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Correct Sidebar Definition
const sidebars: SidebarsConfig = {
  learnSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      collapsible: true,
      collapsed: false,
      items: [
        'learn/intro/what-is-helios',
        'learn/intro/why-helios',
        'learn/intro/key-features',
        'learn/intro/use-cases',
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: false,
      items: [
        'learn/getting-started/overview',
        'learn/getting-started/setting-up-wallet',
        'learn/getting-started/connecting-to-network',
        'learn/getting-started/exploring-ecosystem',
      ],
    },
    {
      type: 'category',
      label: 'Helios Architecture',
      collapsible: true,
      collapsed: false,
      items: [
        'learn/architecture/overview', 
        'learn/architecture/system-design',
        'learn/architecture/consensus-iposr',
        'learn/architecture/security-scalability',
      ],
    },
  ],
  buildSidebar: [
    {
      type: "category",
      label: "Build",
      collapsible: true,
      collapsed: false,
      items: [
        {
          collapsible: true,
          collapsed: false,
          type: "category",
          label: "Running a Node",
          items: [
            "build/running-a-node/system-requirements",
            "build/running-a-node/installation",
            "build/running-a-node/configuration",
            "build/running-a-node/maintaining-upgrading",
          ],
        },
        {
          collapsible: true,
          collapsed: false,
          type: "category",
          label: "Staking & Governance",
          items: [
            "build/staking-governance/staking-mechanics",
            "build/staking-governance/becoming-validator",
            "build/staking-governance/governance-proposals",
            "build/staking-governance/rewards-penalties",
          ],
        },
        {
          collapsible: true,
          collapsed: false,
          type: "category",
          label: "Interchain Operations",
          items: [
            "build/interchain-operations/bridging-assets",
            "build/interchain-operations/hyperion-modules",
            "build/interchain-operations/cross-chain-transactions",
          ],
        },
      ],
    },
  ],
  innovateSidebar: [
    {
      type: 'category',
      label: 'Innovate',
      collapsible: true,
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'innovate' }],
    },
  ],
};

export default sidebars;
