import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Correct Sidebar Definition
const sidebars: SidebarsConfig = {
  learnSidebar: [
    {
      type: 'category',
      label: 'Learn',
      collapsible: true,
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'learn' }],
    },
  ],
  buildSidebar: [
    {
      type: 'category',
      label: 'Build',
      collapsible: true,
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'build' }],
    },
  ],
  innovateSidebar: [
    {
      type: 'category',
      label: 'Innovate',
      collapsible: true,
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'innovate' }],
    },
  ],
};

export default sidebars;
